export const title = 'Your Todo'
export const placeholderText = 'Input todo'
export const checkTitleText = 'Are you sure?'
export const deleteText = 'Delete'
export const cancelText = 'Cancel'
export const allText = 'All'
export const addAltText = 'addIcon'
export const removeAltText = 'removeIcon'
